name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-docker-macos:
    runs-on: macos-latest
    steps:
      - name: Set up Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew install --cask docker
          open /Applications/Docker.app

      - name: Verify Docker installation
        run: docker --version

  test:
    runs-on: ${{ matrix.os }}
    needs: setup-docker-macos
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    services:
      cosmosdb:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
        ports:
          - 8081:8081

    env:
      COSMOSDB_CONNECTION_STRING: ${{ secrets.COSMOSDB_CONNECTION_STRING }}
      COSMOSDB_DATABASE_NAME: ${{ secrets.COSMOSDB_DATABASE_NAME }}
      COSMOSDB_CONTAINER_NAME: ${{ secrets.COSMOSDB_CONTAINER_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Check architecture
        run: uname -m

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
